version: 2
jobs:
  Dev-Terraform-Provisioning:
    docker:
      - image: hashicorp/terraform:0.11.14
        environment:
            TF_WORKSPACE: "dev"
            TF_VERSION: "0.11.14"
            TF_PREFIX: "test-remote-backend-"
            TF_HOSTNAME: "https://app.terraform.io/api/v2"
            TF_ORGANIZATION: "Hashicorp-neh-Demo"
    steps: 
      - checkout
      - run: 
          name: Creating Terraform Enterprise Workspace 
          command: |
            apk add jq
            tee payload_ws.json <<EOF
              {
                "data": {
                  "attributes": {
                    "name": "$TF_PREFIX$TF_WORKSPACE",
                    "terraform_version": "$TF_VERSION"
                  },
                  "type": "workspaces"
                }
              }
            EOF
            TF_WORKSPACE_ID="$(curl -v -H "Authorization: Bearer ${tfe_token}" -H "Content-Type: application/vnd.api+json" -d "@./payload_ws.json" "${TF_HOSTNAME}/organizations/${TF_ORGANIZATION}/workspaces" | jq -r '.data.id')"
            echo "TF_WORKSPACE_ID=$TF_WORKSPACE_ID" >> $BASH_ENV
            echo $BASH_ENV
      - run:
          name: Adding Variables to Terraform Workspace
          command: |
            tee payload_vars.json <<EOF
              {
                "data": {
                  "type":"vars",
                  "attributes": {
                    "key":"env",
                    "value":"dev",
                    "category":"terraform",
                    "hcl":false,
                    "sensitive":false
                  },
                  "relationships": {
                    "workspace": {
                      "data": {
                        "id":"${TF_WORKSPACE_ID}",
                        "type":"workspaces"
                      }
                    }
                  }
                }
              }
            EOF
            curl -v -H "Authorization: Bearer ${tfe_token}" -H "Content-Type: application/vnd.api+json" -d "@./payload_vars.json" "${TF_HOSTNAME}/vars"  
      - run:
          name: Terraform Initialization
          command: terraform init -input=false -backend-config="token=$tfe_token"
      - run:
          name: Validate Terraform Code
          command: terraform validate
      - run:
          name: Terraform Plan
          command: |
              terraform plan -input=false
      - run:
          name: Terraform Apply
          command: terraform apply -input=false -auto-approve
  Prod-Terraform-Provisioning:
    docker:
      - image: hashicorp/terraform:0.11.14
        environment:
          TF_WORKSPACE: "prod"
    steps: 
      - checkout
      - run:
          name: Terraform Initialization
          command: terraform init -input=false -backend-config="token=$tfe_token"
      - run:
          name: Validate Terraform Code
          command: terraform validate
      - run:
          name: Terraform Plan
          command: |
            terraform plan -input=false
      - run:
          name: Terraform Apply
          command: terraform apply -input=false -auto-approve
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - Dev-Terraform-Provisioning
    - Approve-Dev-To-Prod:
        type: approval
        requires: 
          - Dev-Terraform-Provisioning
    - Prod-Terraform-Provisioning:
        requires: 
          - Approve-Dev-To-Prod

     