version: 2
jobs:
  Dev-Terraform-Provisioning:
    docker:
      - image: hashicorp/terraform:0.11.14
        environment:
            TF_WORKSPACE: "dev"
            TF_VERSION: "0.11.14"
            TF_PREFIX: "remote-backend-"
            TF_HOSTNAME: "https://app.terraform.io/api/v2"
            TF_ORGANIZATION: "Hashicorp-neh-Demo"
    steps: 
      - checkout
      - run: 
          name: Creating Terraform Enterprise Workspace 
          command: |
            tee payload.json <<EOF
              {
                "data": {
                  "attributes": {
                    "name": "$TF_PREFIX$TF_WORKSPACE",
                    "terraform_version": "$TF_VERSION"
                  },
                  "type": "workspace"
                }
              }
              EOF
            TF_WORKSPACE_ID="$(curl -v --header "Authorization: Bearer ${tfe_token}" --header "Content-Type: application/vnd.api+json" -d "@./payload.json" "${TF_HOSTNAME}/${TF_ORGANIZATION}" | jq -r '.id')"
            echo $TF_WORKSPÄCE_ID
      - run:
          name: Terraform Initialization
          command: terraform init -input=false -backend-config="token=$tfe_token"
      - run:
          name: Validate Terraform Code
          command: terraform validate
      - run:
          name: Terraform Plan
          command: |
              terraform plan -input=false
      - run:
          name: Terraform Apply
          command: terraform apply -input=false -auto-approve
  Prod-Terraform-Provisioning:
    docker:
      - image: hashicorp/terraform:0.11.14
        environment:
          TF_WORKSPACE: "prod"
    steps: 
      - checkout
      - run:
          name: Terraform Initialization
          command: terraform init -input=false -backend-config="token=$tfe_token"
      - run:
          name: Validate Terraform Code
          command: terraform validate
      - run:
          name: Terraform Plan
          command: |
            terraform plan -input=false
      - run:
          name: Terraform Apply
          command: terraform apply -input=false -auto-approve
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - Dev-Terraform-Provisioning
    - Approve-Dev-To-Prod:
        type: approval
        requires: 
          - Dev-Terraform-Provisioning
    - Prod-Terraform-Provisioning:
        requires: 
          - Approve-Dev-To-Prod

     