version: 2
jobs:
  Validate-Code:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - run:
          name: Validate Terraform Code
          command: terraform validate
  Terraform-Init:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps: 
      - checkout
      - run:
          name: Terraform Initialization
          command: terrafom init
  Terraform-Plan:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps: 
      - checkout
      - run:
          name: Terraform Plan
          command: terrafom plan
  Terraform-Apply:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps: 
      - checkout
      - run:
          name: Terraform Apply
          command: terrafom apply
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - Validate-Code
    - Terraform-Init:
        requires:
        - Validate-Code
    - Terraform-Plan:
        requires:
        - Terraform-Init
    - Terraform-Apply:
        requires:
        - Terraform-Plan 
     